import pprint
import collections
from dependenpy.utils import DependencyMatrix

MATRIX_PACKAGE_LIST = collections.OrderedDict()
MATRIX_PACKAGE_LIST['Odoo account'] = [
    'account',
    'account_accountant',
    'account_analytic_analysis',
    'account_analytic_default',
    'account_analytic_plans',
    'account_anglo_saxon',
    'account_asset',
    'account_bank_statement_extensions',
    'account_budget',
    'account_cancel',
    'account_chart',
    'account_check_writing',
    'account_followup',
    'account_payment',
    'account_sequence',
    'account_test',
    'account_voucher',
]

MATRIX_PACKAGE_LIST['Odoo base'] = [
    'base',
    'base_action_rule',
    'base_gengo',
    'base_geolocalize',
    'base_iban',
    'base_import',
    'base_import_module',
    'base_report_designer',
    'base_setup',
    'base_vat',
]

MATRIX_PACKAGE_LIST['Odoo HR/HW'] = [
    'hr',
    'hr_applicant_document',
    'hr_attendance',
    'hr_contract',
    'hr_evaluation',
    'hr_expense',
    'hr_gamification',
    'hr_holidays',
    'hr_payroll',
    'hr_payroll_account',
    'hr_recruitment',
    'hr_timesheet',
    'hr_timesheet_invoice',
    'hr_timesheet_sheet',
    'hw_escpos',
    'hw_posbox_homepage',
    'hw_posbox_upgrade',
    'hw_proxy',
    'hw_scale',
    'hw_scanner',
]

MATRIX_PACKAGE_LIST['Odoo L10N'] = [
    'l10n_ae',
    'l10n_ar',
    'l10n_at',
    'l10n_be',
    'l10n_be_coda',
    'l10n_be_hr_payroll',
    'l10n_be_hr_payroll_account',
    'l10n_be_intrastat',
    'l10n_be_invoice_bba',
    'l10n_bo',
    'l10n_br',
    'l10n_ca',
    'l10n_ch',
    'l10n_cl',
    'l10n_cn',
    'l10n_co',
    'l10n_cr',
    'l10n_de',
    'l10n_do',
    'l10n_ec',
    'l10n_es',
    'l10n_et',
    'l10n_eu_service',
    'l10n_fr',
    'l10n_fr_hr_payroll',
    'l10n_fr_rib',
    'l10n_gr',
    'l10n_gt',
    'l10n_hn',
    'l10n_hr',
    'l10n_hu',
    'l10n_in',
    'l10n_in_hr_payroll',
    'l10n_it',
    'l10n_lu',
    'l10n_ma',
    'l10n_multilang',
    'l10n_mx',
    'l10n_nl',
    'l10n_no',
    'l10n_pa',
    'l10n_pe',
    'l10n_pl',
    'l10n_pt',
    'l10n_ro',
    'l10n_sg',
    'l10n_si',
    'l10n_syscohada',
    'l10n_th',
    'l10n_tr',
    'l10n_uk',
    'l10n_us',
    'l10n_uy',
    'l10n_ve',
    'l10n_vn',
]

MATRIX_PACKAGE_LIST['Odoo Web'] = [
    'web',
    'web_api',
    'web_calendar',
    'web_diagram',
    'web_gantt',
    'web_graph',
    'web_kanban',
    'web_kanban_gauge',
    'web_kanban_sparkline',
    'web_linkedin',
    'website',
    'website_blog',
    'website_certification',
    'website_crm',
    'website_crm_partner_assign',
    'website_customer',
    'website_event',
    'website_event_sale',
    'website_event_track',
    'website_forum',
    'website_forum_doc',
    'website_gengo',
    'website_google_map',
    'website_hr',
    'website_hr_recruitment',
    'website_instantclick',
    'website_livechat',
    'website_mail',
    'website_mail_group',
    'website_membership',
    'website_partner',
    'website_payment',
    'website_project',
    'website_quote',
    'website_report',
    'website_sale',
    'website_sale_delivery',
    'website_sale_options',
    'website_twitter',
    'web_tests',
    'web_tests_demo',
    'web_view_editor',
]

MATRIX_PACKAGE_LIST['Odoo Miscellaneous'] = [
    'analytic',
    'analytic_contract_hr_expense',
    'analytic_user_function',
    'anonymization',
    'association',
    'auth_crypt',
    'auth_ldap',
    'auth_oauth',
    'auth_openid',
    'auth_signup',
    'board',
    'bus',
    # 'calendar',
    'claim_from_delivery',
    'contacts',
    'crm',
    'crm_claim',
    'crm_helpdesk',
    'crm_mass_mailing',
    'crm_partner_assign',
    'crm_profiling',
    'crm_project_issue',
    'decimal_precision',
    'delivery',
    'document',
    'edi',
    'email_template',
    'event',
    'event_sale',
    'fetchmail',
    'fleet',
    'gamification',
    'gamification_sale_crm',
    'google_account',
    'google_calendar',
    'google_drive',
    'google_spreadsheet',
    'im_chat',
    'im_livechat',
    'im_odoo_support',
    'knowledge',
    'lunch',
    'mail',
    '_markerlib',
    'marketing',
    'marketing_campaign',
    'marketing_campaign_crm_demo',
    'marketing_crm',
    'mass_mailing',
    'membership',
    'mrp',
    'mrp_byproduct',
    'mrp_operations',
    'mrp_repair',
    'multi_company',
    'note',
    'note_pad',
    'pad',
    'pad_project',
    'payment',
    'payment_adyen',
    'payment_buckaroo',
    'payment_ogone',
    'payment_paypal',
    'payment_transfer',
    'point_of_sale',
    'portal',
    'portal_claim',
    'portal_gamification',
    'portal_project',
    'portal_project_issue',
    'portal_sale',
    'portal_stock',
    'pos_discount',
    'pos_restaurant',
    'procurement',
    'procurement_jit',
    'product',
    'product_email_template',
    'product_expiry',
    'product_extended',
    'product_margin',
    'product_visible_discount',
    'project',
    'project_issue',
    'project_issue_sheet',
    'project_timesheet',
    'purchase',
    'purchase_analytic_plans',
    'purchase_double_validation',
    'purchase_requisition',
    'report',
    'report_intrastat',
    'report_webkit',
    'resource',
    'sale',
    'sale_analytic_plans',
    'sale_crm',
    'sale_journal',
    'sale_layout',
    'sale_margin',
    'sale_mrp',
    'sale_order_dates',
    'sale_service',
    'sales_team',
    'sale_stock',
    'setuptools',
    'setuptools-3.6.dist-info',
    'share',
    'six-1.9.0.dist-info',
    'stock',
    'stock_account',
    'stock_dropshipping',
    'stock_invoice_directly',
    'stock_landed_costs',
    'stock_picking_wave',
    'subscription',
    'survey',
    'survey_crm',
    'test_access_rights',
    'test_convert',
    'test_converter',
    'test_documentation_examples',
    'test_exceptions',
    'test_impex',
    'test_inherit',
    'test_limits',
    'test_new_api',
    'test_uninstall',
    'test_workflow',
    'warning',
]

dm = DependencyMatrix(MATRIX_PACKAGE_LIST)
dm.build_modules()
dm.build_imports()
dm.build_matrices()


OPTIONS = {
    'group_name': False,
    'group_index': True,
    'source_name': False,
    'source_index': True,
    'target_name': False,
    'target_index': True,
    'imports': False,
    'cardinal': True,
}

pp = pprint.PrettyPrinter(indent=2)
# pp.pprint(dm.modules)
# pp.pprint(dm.max_depth)
pp.pprint(dm.matrix_to_json(1, OPTIONS))
# pp.pprint(dm.matrices[1])


# print dm.matrix_to_csv(1)
